### ISSUE TITLE
Don't use JWTs for authentication (security risk)

### ISSUE THREAD

**Issue by ghchaosfae** [openauthjs/openauth#24]
This system should not be using JWTs, and specifically shouldn't be using access tokens + refresh tokens.

Refresh tokens are a form of server side sessions, and server side sessions by itself is what should be used here. Client servers should receive a single token from OpenAuth which can be verified with subsequent requests to OpenAuth. If the apps have their own local user management and need to get a user ID, then the server should be responding with that, and the client server should put the user ID in the session data for the user (after regenerating the session, per normal security requirements for sessions). For those cases, it seems like perhaps oauth isn't necessarily what's actually needed, since oauth is meant for providing credentials for accessing resources that the oauth server is also the authenticator for (.e.g, you use github oauth as a client server so that you can make requests to github on behalf of the user. authenticating your user as a specific github user is more or less a side effect).

Persistent stateless authentication (access tokens verified using a single stored key for many tokens) has very high risks and should not be used, especially not with very long default expiration times (such as 1 month: https://github.com/openauthjs/openauth/blob/master/packages/openauth/src/authorizer.ts#L100).

References:
- http://cryto.net/~joepie91/blog/2016/06/13/stop-using-jwt-for-sessions/
- https://gist.github.com/samsch/0d1f3d3b4745d778f78b230cf6061452 (this references out to several other sources more easily verifiable as security folk)

**Comment by thdxr** [comment]
these things were considered and i'll lay out the thinking here

JWTs aren't innately problematic - they come with the tradeoff of not being able to be revoked. The ideal setup is setting a short expiry time on the access_token (eg 5min) and setting a long expiry on the refresh token (which is not a JWT and can be revoked).

that means once you revoke a refresh token there is a 5min window max that the credential can still be used. We will likely switch the defaults to this once we leave beta and have proper APIs for revoking refresh tokens.

the upside of JWT is that they can be verified in many places without making a call to the central server. eg you can setup AWS API Gateway with JWT Authorization which just needs to fetch the public key from OpenAuth once and it can verify as many requests on its own

the problem with security related projects is they attract a lot of "X is bad" type of commentary. security is not a binary thing - it is a product like anything else. there's always a spectrum of usability and security that needs to be considered. infinitely optimizing for "security" does not land in a good place.

since this repo is new i want to lay down this policy: if you have a security related commentary it needs to be submitted with this perspective - otherwise the issue will be closed without response. i do not want to get bogged down explaining why extreme views that "x is bad" needs nuance

**Comment by thdxr** [comment]
i explained the design above with the exact tradeoff - it's worth noting that clerk documents a very similar design in their system which also uses JWTs: https://clerk.com/blog/combining-the-benefits-of-session-tokens-and-jwts

given they have a large team dedicated to this i recommend filing an issue with clerk - given you are confident that JWTs are always bad for auth i am sure they will rework their whole system based on your recommendations

i also believe keycloak does the same approach so can file an issue there as well

if something about the design of these systems differs let me know and im happy to review

but i do agree, it's not obvious we are in beta, we will make that more clear
